commerce_payment.commerce_payment_gateway.plugin.alipay_customer_scan_qrcode_pay:
  type: commerce_payment_gateway_configuration
  mapping:
    app_id:
      type: string
      label: 'app_id'
    private_key:
      type: string
      label: 'private_key'
    public_key:
      type: string
      label: 'public_key'
    app_auth_token:
      type: string
      label: 'app_auth_token'
    sys_service_provider_id:
      type: string
      label: 'sys_service_provider_id'

commerce_payment.commerce_payment_gateway.plugin.alipay_business_capture_qrcode_pay:
  type: commerce_payment_gateway_configuration
  mapping:
    app_id:
      type: string
      label: 'app_id'
    private_key:
      type: string
      label: 'private_key'
    public_key:
      type: string
      label: 'public_key'
    app_auth_token:
      type: string
      label: 'app_auth_token'
    sys_service_provider_id:
      type: string
      label: 'sys_service_provider_id'
