name: OpenAPI
type: module
description: Connects Drupal to the OpenAPI Javascript Library
# core: 8.x
package: OpenAPI
dependencies:
  - schemata:schemata
  - schemata:schemata_json_schema

# Information added by Drupal.org packaging script on 2019-06-27
version: '8.x-1.0-beta4'
core: '8.x'
project: 'openapi'
datestamp: 1561648404
