field.storage_settings.pinyin_shortcode:
  type: field.storage_settings.string
  label: 'Pinyin shortcode settings'

field.field_settings.pinyin_shortcode:
  type: mapping
  label: 'Pinyin shortcode settings'

field.value.pinyin_shortcode:
   type: mapping
   label: 'Default value'
   mapping:
     value:
       type: string
       label: 'Value'
